import { QuartzConfig } from "./quartz/cfg"
import * as Plugin from "./quartz/plugins"

// https://github.com/morhetz/gruvbox
const GRUVBOX_COLORS = {
  DARK: {
    bg_0: "#282828",
    red_1: "#cc241d",
    green_2: "#98971a",
    yellow_3: "#d79921",
    blue_4: "#458588",
    purple_5: "#b16286",
    aqua_6: "#689d6a",
    gray_7: "#7c6f64",
    gray_8: "#928374",
    red_9: "#fb4934",
    green_10: "#b8bb26",
    yellow_11: "#fabd2f",
    blue_12: "#83a598",
    purple_13: "#d3869b",
    aqua_14: "#8ec07c",
    fg_15: "#ebdbb2",
    bg0_h: "#1d2021",
    bg0: "#282828",
    bg1: "#3c3836",
    bg2: "#504945",
    bg3: "#665c54",
    bg4: "#7c6f64",
    gray: "#928374",
    orange_1: "#d65d0e",
    bg0_s: "#32302f",
    fg4: "#a89984",
    fg3: "#bdae93",
    fg2: "#d5c4a1",
    fg1: "#ebdbb2",
    fg0: "#fbf1c7",
    orange_2: "#fe8019",
  },
  LIGHT: {
    bg_0: "#fbf1c7",
    red_1: "#cc241d",
    green_2: "#98971a",
    yellow_3: "#d79921",
    blue_4: "#458588",
    purple_5: "#b16286",
    aqua_6: "#689d6a",
    gray_7: "#7c6f64",
    gray_8: "#928374",
    red_9: "#9d0006",
    green_10: "#79740e",
    yellow_11: "#B57614",
    blue_12: "#076678",
    purple_13: "#8F3F71",
    aqua_14: "#427B58",
    fg_15: "#3C3836",
    bg0_h: "#F9F5D7",
    bg0: "#FBF1C7",
    bg1: "#EBDBB2",
    bg2: "#D5C4A1",
    bg3: "#BDAE93",
    bg4: "#A89984",
    gray: "#928374",
    orange_1: "#D65D0E",
    bg0_s: "#F2E5BC",
    fg4: "#7C6F64",
    fg3: "#665C54",
    fg2: "#504945",
    fg1: "#3C3836",
    fg0: "#282828",
    orange_2: "#AF3A03",
  },
}

/**
 * Quartz 4.0 Configuration
 *
 * See https://quartz.jzhao.xyz/configuration for more information.
 */
const config: QuartzConfig = {
  configuration: {
    pageTitle: "shakhzod's website",
    pageTitleSuffix: " | shakhzod's website",
    enableSPA: true,
    enablePopovers: true,
    analytics: null,
    locale: "en-US",
    baseUrl: "shakhzod.me",
    ignorePatterns: ["private", "templates", ".obsidian"],
    defaultDateType: "created",
    theme: {
      fontOrigin: "googleFonts",
      cdnCaching: true,
      typography: {
        header: "Schibsted Grotesk",
        body: "Source Sans Pro",
        code: "JetBrains Mono",
      },
      colors: {
        lightMode: {
          light: GRUVBOX_COLORS.LIGHT.bg0_h,
          lightgray: GRUVBOX_COLORS.LIGHT.bg2,
          gray: GRUVBOX_COLORS.LIGHT.fg3,
          darkgray: GRUVBOX_COLORS.LIGHT.fg_15,
          dark: GRUVBOX_COLORS.LIGHT.fg0,
          secondary: GRUVBOX_COLORS.LIGHT.blue_12,
          tertiary: GRUVBOX_COLORS.LIGHT.aqua_14,
          highlight: "rgba(143, 159, 169, 0.15)",
          textHighlight: "#fff23688",
        },
        darkMode: {
          light: GRUVBOX_COLORS.DARK.bg0_h,
          lightgray: GRUVBOX_COLORS.DARK.bg2,
          gray: GRUVBOX_COLORS.DARK.fg3,
          darkgray: GRUVBOX_COLORS.DARK.fg_15,
          dark: GRUVBOX_COLORS.DARK.fg0,
          secondary: GRUVBOX_COLORS.DARK.green_10,
          tertiary: GRUVBOX_COLORS.DARK.blue_12,
          highlight: "rgba(143, 159, 169, 0.15)",
          textHighlight: "#b3aa0288",
        },
      },
    },
  },
  plugins: {
    transformers: [
      Plugin.FrontMatter(),
      Plugin.CreatedModifiedDate({
        priority: ["frontmatter", "filesystem"],
      }),
      Plugin.SyntaxHighlighting({
        theme: {
          light: "github-light",
          dark: "github-dark",
        },
        keepBackground: false,
      }),
      Plugin.ObsidianFlavoredMarkdown({ enableInHtmlEmbed: false }),
      Plugin.GitHubFlavoredMarkdown(),
      Plugin.TableOfContents(),
      Plugin.CrawlLinks({ markdownLinkResolution: "shortest" }),
      Plugin.Description(),
      Plugin.Latex({ renderEngine: "katex" }),
    ],
    filters: [Plugin.RemoveDrafts()],
    emitters: [
      Plugin.AliasRedirects(),
      Plugin.ComponentResources(),
      Plugin.ContentPage(),
      Plugin.FolderPage(),
      Plugin.TagPage(),
      Plugin.ContentIndex({
        enableSiteMap: true,
        enableRSS: true,
      }),
      Plugin.Assets(),
      Plugin.Static(),
      Plugin.NotFoundPage(),
    ],
  },
}

export default config
